### ISSUE TITLE
Add context to all callbacks

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#106]
Version: 3.x-feature
Original reporter: 

Continue bug#66.

Another example is the mxmlSetErrorCallback() which has no context assigned. It would be much easier to use if there is ability to set some void* context.

Also, I am not sure I understand why the error callback is thread specific.

This kind of library usually needs no global context. First argument of every function may provide the necessary context.

For the error callback, except of context it would be nice to get a details of the object that caused the error, or have a separate callback for errors during parsing. For example, if I parse 3 XML I want to present a different messages for each [without using globals].

Thanks

**Comment by michaelrsweet** [comment]
Not for 3.0...

**Comment by AaronLasseigne** [comment]
I'm in the process of writing an mruby gem that uses this library. I would love to see this happen. I'm looking to catch errors and bubble them up through mruby but I need to be able to provide context to do that. So, 👍 from me!

**Comment by michaelrsweet** [comment]
This is now part of Git master for 4.0.
