### ISSUE TITLE
mxmlGetCDATA BUG

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#153]
Version: 2.7
Original reporter: 

function: mxmlGetCDATA()
  if (...)
    return (NULL);
  return (node->value.element.name + 8);

function: mxmlSetCDATA()
  if ( ... )
    node = node->child;
  ...  
  node->value.element.name = _mxml_strdupf("![CDATA[%s]]", data);      

Rules are not consistent

**Comment by frozenpeak2018** [comment]
2.11
mxmlGetCDATA:
if (!node || node->type != MXML_ELEMENT ||
     strncmp(node->value.element.name, "![CDATA[", 8))
  return (NULL);
return (node->value.element.name + 8);

we cannot get the CDATA element by checking "node->value.element.name".
the "node->child->next" is the CDATA element. the following code can resolve this problem :
mxml_node_t *cdata = NULL;

if (!node || node->type != MXML_ELEMENT)
{
    return NULL;
}
  for (node = node->child; node; node = node->next)
  {
      if (node->type == MXML_ELEMENT && !strncmp(node->value.element.name, "![CDATA[", 8))
      {
          cdata = node;
          break;
      }
  }
return (cdata ? (cdata->value.element.name+8) : NULL);

is this solution feasible?

**Comment by michaelrsweet** [comment]
@frozenpeak2018 Please file a new bug report if you are having trouble with the current release.
