### ISSUE TITLE
mem leak while mxmlDelete

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#183]
Version: 2.10
Original reporter: Franco yin

test code:
```
	pDoc = mxmlNewXML("1.0");
	pRoot = mxmlNewElement(pDoc, "root");
	pNode1 = mxmlNewElement(pRoot, "lev1");
	mxmlDelete(pDoc);
```
mxmlDelete won't free the node "root"

in function mxmlDelete, source code like this:
```
    if ((next = current->next) == NULL)
    {
      mxml_node_t *temp = current->parent;
					/* Pointer to parent node */

      if (temp == node)
      {
       /*
        * Got back to the top node...
        */

        next = NULL;
      }
      else if ((next = temp->next) == NULL)
      {
		if ((next = temp->parent) == node)
		  next = NULL;
      }
    }
```

I think it should be like this, notice "if ((next = temp) == node":
```
    if ((next = current->next) == NULL)
    {
      mxml_node_t *temp = current->parent;
					/* Pointer to parent node */

      if (temp == node)
      {
       /*
        * Got back to the top node...
        */

        next = NULL;
      }
      else if ((next = temp->next) == NULL)
      {
		if ((next = temp) == node)
		  next = NULL;
      }
    }
```

**Comment by bipbip59** [comment]
sorry for the duplicate and the  recursion.

I use the last version (V2.11).  I can not understand if this version included or not the patch?
`/*
 * 'mxmlDelete()' - Delete a node and all of its children.
 *
 * If the specified node has a parent, this function first removes the
 * node from its parent using the mxmlRemove() function.
 */

void
mxmlDelete(mxml_node_t *node)		/* I - Node to delete */
{
  mxml_node_t	*current,		/* Current node */
		*next;			/* Next node */


#ifdef DEBUG
  fprintf(stderr, "mxmlDelete(node=%p)\n", node);
#endif /* DEBUG */

 /*
  * Range check input...
  */

  if (!node)
    return;

 /*
  * Remove the node from its parent, if any...
  */

  mxmlRemove(node);

 /*
  * Delete children...
  */

  for (current = node->child; current; current = next)
  {
   /*
    * Get the next node...
    */

    if ((next = current->child) != NULL)
    {
     /*
      * Free parent nodes after child nodes have been freed...
      */

      current->child = NULL;
      continue;
    }

    if ((next = current->next) == NULL)
    {
      mxml_node_t *temp = current->parent;
					/* Pointer to parent node */

      if (temp == node)
      {
       /*
        * Got back to the top node...
        */

        next = NULL;
      }
      else if ((next = temp->next) == NULL)
      {
	if ((next = temp->parent) == node)
	  next = NULL;
      }
    }

    mxml_free(current);
  }

 /*
  * Then free the memory used by this node...
  */

  mxml_free(node);
}

`

If so it does not work at home, if not can you get back the patch that works please?
I could in this case validate it with my application.
Tahnk's

**Comment by bipbip59** [comment]
Whatever your answer, I think I have found a solution without recursion.

- As long as a child node has itself a child, this "child child" is moved after the child node to be deleted.
- The nud child who has no child is free.
- We go to the next child node ...

`
void mxmlDelete(mxml_node_t *node)
{
   mxml_node_t	*current,*next;
   if (!node)  return;
  while ((current = node->child)!=NULL)
  {
	  while ((next=current->child)!=NULL)
	  {
		 mxmlRemove(next);
		 mxmlAdd(node,MXML_ADD_AFTER,current,next);
	  }
	  mxmlRemove(current);
	  mxml_free(current);
  }
  mxmlRemove(node);
  mxml_free(node);
}
`

**Comment by michaelrsweet** [comment]
Fixed in git repo:

```
    if ((next = current->next) == NULL)
    {
     /*
      * Next node is the parent, which we'll free as needed...
      */

      if ((next = current->parent) == node)
        next = NULL;
    }
```
