### ISSUE TITLE
get all attributes

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#185]
Version: -feature
Original reporter: Loo

Hi,

as an idea (because I needed that) perhaps this is useful to other people too.
I wanted to have all attributes to an element w/o name reference. I fetch the count via mxmlElementGetAttrCount (see below) and handover a pointer array with 2*count*sizeof(char *) to mxmlElementGetAllAttr which fills in the references to the name/value pairs.
This was added to mxml_attr.c for version 2.10

Greetings
Otto

---
```
void mxmlElementGetAllAttr(mxml_node_t *node, char **pa)
{
  int		i;			/* Looping var */
  mxml_attr_t	*attr;			/* New attribute */

  if (!node || node->type != MXML_ELEMENT)
    return;

  for (i = node->value.element.num_attrs, attr = node->value.element.attrs;
       i > 0;
       i --, attr ++)
  {
	*pa++ = attr->name;
	*pa++ = attr->value;
  }
}

int mxmlElementGetAttrCount(mxml_node_t *node)
{
  if (!node || node->type != MXML_ELEMENT)
    return (-1);

  return (node->value.element.num_attrs);
}
```

**Comment by michaelrsweet** [comment]
Probably better to add an API for getting an attribute name by index, so that you can grab things one at a time.

**Comment by loo66** [comment]
take care ... it seems when moving the article some '*' got lost ...

**Comment by michaelrsweet** [comment]
Fixed...

**Comment by michaelrsweet** [comment]
[master 48c3c62] Add mxmlElementAttrGetByIndex and mxmlElementAttrGetCount (Issue #185)
