### ISSUE TITLE
Cross-compiling Windows DLL using MingW on Linux

### ISSUE THREAD

**Issue by tehnick** [michaelrsweet/mxml#188]
Please add ability to cross-compile mxml as a shared library for MS Windows.

Currently your library is packaged by [MXE](http://mxe.cc/) project but only for [static targets](https://github.com/mxe/mxe/blob/master/src/mxml.mk).
Also this will be [useful](https://github.com/gkdr/libomemo/issues/9) for [libomemo](https://github.com/gkdr/libomemo) project.

**Comment by michaelrsweet** [comment]
Shared library creation is highly system-specific, so I don't see doing this for any platform.

It is conceivable that I could support cross-compiling for a Linux shared library target but even that might not work with all cross-compile tools... :/

**Comment by michaelrsweet** [comment]
[master 2b94fdd] Add (limited) cross-compilation support (Issue #188)

**Comment by michaelrsweet** [comment]
OK, try grabbing the latest code from master and let me know if you have any issues.

**Comment by tehnick** [comment]
```
...
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `mxml.list.in'
```

**Comment by asavah** [comment]
This made things worse.
Before I was able to cross build mxml shared library with a little patch,
now it will fail.
```
configure: WARNING: shared libraries not supported on this platform.
```
```
config.status: error: cannot find input file: `mxml.list.in'
```

Shared lib support detection is wrong and completely bogus
This is total nonsense -> https://github.com/michaelrsweet/mxml/blob/master/configure.ac#L171
Even when running configure without crosscompiling the shared check fails.
In my case host_os is  linux-gnu ( its Ubuntu 16.10 x64) which will not pass the check below which check only for "linux" verbatim.

**Comment by asavah** [comment]
The patch below and running autoconf -v before ./configure fixed cross build again for me:
```
diff --git a/Makefile.in b/Makefile.in
index 5fbc383..ebb32c5 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -16,7 +16,7 @@
 # Compiler tools definitions...
 #

-AR             =       @AR@
+AR             :=      $(AR)
 ARFLAGS                =       @ARFLAGS@
 ARCHFLAGS      =       @ARCHFLAGS@
 CC             =       @CC@
@@ -31,7 +31,7 @@ LIBS          =       @LIBS@ @PTHREAD_LIBS@
 LN             =       @LN@ -s
 MKDIR          =       @MKDIR@
 OPTIM          =       @OPTIM@
-RANLIB         =       @RANLIB@
+RANLIB         :=      $(RANLIB)
 RM             =       @RM@ -f
 SHELL          =       /bin/sh

@@ -55,7 +55,7 @@ BUILDROOT     =       $(DSTROOT)
 # Install commands...
 #

-INSTALL_BIN    =       $(LIBTOOL) $(INSTALL) -m 755 -s
+INSTALL_BIN    =       $(LIBTOOL) $(INSTALL) -m 755
 INSTALL_DATA   =       $(INSTALL) -m 644
 INSTALL_DIR    =       $(INSTALL) -d
 INSTALL_LIB    =       $(LIBTOOL) $(INSTALL) -m 755
diff --git a/configure.ac b/configure.ac
index e8c9919..172d0b5 100644
--- a/configure.ac
+++ b/configure.ac
@@ -192,7 +192,7 @@ if test x$enable_shared != xno; then
                        DSOFLAGS="$DSOFLAGS -Wl,-rpath,\$(libdir),-set_version,sgi1.0,-soname,libmxml.so.1 -shared \$(OPTIM)"
                        ;;

-               osf | linux | gnu)
+               osf | linux-gnu*)
                        AC_MSG_RESULT(yes)
                        LIBMXML="libmxml.so.1.5"
                        DSO="\$(CC)"
```

**Comment by michaelrsweet** [comment]
OK, the patch is wrong.

And the reason I asked you to check is that I *don't* have you configuration handy and am unable to test it myself (although I should have gotten the missing mxml.list.in file error...  hmmm..)

Try the latest now.  I *did* push both an updated configure.ac and configure script; I haven't checked install-sh to verify it does the right thing for -s (strip), I suspect that might still be a problem.

**Comment by michaelrsweet** [comment]
(I updated the ar check to use AC_CHECK_TOOL which handles the host tool prefix nonsense, and AC_PROG_RANLIB is supposed to do that already...)

**Comment by michaelrsweet** [comment]
OK, lacking a better solution I've dropped the -s option from the INSTALL_BIN definition to avoid using the wrong strip command on install. Please let me know if you run into any problems!

**Comment by asavah** [comment]
Thanks.
At least for me latest master built without problems and dirty hacks.

**Comment by michaelrsweet** [comment]
Great!

**Comment by tehnick** [comment]
Why this issue was closed? You have not added `libmxml.dll` target into `Makefile.in` and appropriate check for shared library support into `configure` script.

As far as I see currently there is only one possible way to build *.dll file for MS Windows: using MS Visual Studio. I am just asking for adding MinGW support... As far as I know in autotools based projects it is quite easy to do.

**Comment by michaelrsweet** [comment]
@tehnick You didn't ask to be able to build a DLL via cross-compilation, you asked for cross-compilation via MingW and showed the example of building a Linux shared library. I will investigate possibilities for supporting creation of a Windows DLL via cross-compilation, but right now I only support doing so using the Visual Studio project file (and Visual Studio Essentials is a FREE download).

For the record, libtool and automake are compatibility nightmares, so I will NEVER support them. libtool fails on many platforms and introduces complications for using the shared libraries with non-autotools projects (works for common platforms, not so well for anything else). And automake can create makefiles that are not compatible with regular "make" programs like supplied with Visual Studio, some BSDs, HP-UX, IRIX, Solaris, AIX, etc. In short, using the full autotools suite can make a program less portable and harder to maintain, especially if you are not willing to require the use of GNU make.

**Comment by tehnick** [comment]
> For the record, libtool and automake are compatibility nightmares, so I will NEVER support them.

I see.

Personally I do not like autotools at all and use cmake in all projects where it is possible.

> You didn't ask to be able to build a DLL via cross-compilation, you asked for cross-compilation via MingW

Sorry if my description was not enough accurate.

> and showed the example of building a Linux shared library.

I am not sure what are you talking about. [MXE project](http://mxe.cc/) is developed by Linux, macOS and *BSD users for simplifying cross-compilation of libraries and applications for MS Windows.

> I will investigate possibilities for supporting creation of a Windows DLL via cross-compilation,

Thanks a lot.

> but right now I only support doing so using the Visual Studio project file (and Visual Studio Essentials is a FREE download).

Unfortunately this is useless for developers without MS Windows.

**Comment by tonytheodore** [comment]
See #192, `cmake` takes care of a lot when it comes to building shared libs for windows.

**Comment by greendow** [comment]
If a user can use MS Visual Studio, he can complie and build mini-XML shared library with Visual Studio command prompt. I wrote an introduction. It can be found in my blog: http://blog.csdn.net/henter/article/details/53907696
I also sent an email to the mini-XML developer to suggest including the introduction in mini-XML documentation,  but I got no response.

**Comment by michaelrsweet** [comment]
I just pushed the following changes to support building DLLs:

[master 3700ebd] Add libmxml1.dll target and support for mingw cross-compilation (Issue #188)

Please let me know whether they work for you...

**Comment by michaelrsweet** [comment]
@tehnick Can you test the changes in master and let me know if things are working satisfactorily?

**Comment by michaelrsweet** [comment]
Please let me know if this does not work for you.

**Comment by Neustradamus** [comment]
Any news?
