### ISSUE TITLE
Improve/clarify documentation concerning mxmlGetText vs. mxmlGetOpaque

### ISSUE THREAD

**Issue by lirunlong** [michaelrsweet/mxml#190]
eg. \<status\>abc   def\</status\>

    mxml_node_t * status = mxmlFindElement(...);
    const char * text = mxmlGetText(status, 0);
    
    I am looking forward to get a string  "abc  def"  , but returned only "abc" , 
    Is there another way to get "abc def"?

**Comment by michaelrsweet** [comment]
I need to make this more visible somehow, it is by far the most frequently asked question when using Mini-XML...

The MXML_TEXT type provides whitespace-delimited text values, so in your example there will be two child (text value) nodes: "abc" and "def".

If you want to get opaque text strings then you want to use the MXML_OPAQUE type for children of your element. When loading the XML you can use the MXML_OPAQUE_CALLBACK callback or your own that returns MXML_OPAQUE for this particular element. Then you'll use mxmlGetOpaque(status) to get the string, including all whitespace, etc.

**Comment by aespinoza** [comment]
@michaelrsweet There definitely needs more information on this somewhere in the main documentation. I stumbled upon this problem too and it took me a while to figure it out.

The solution in here actually helped me a lot. Thank you.

**Comment by michaelrsweet** [comment]
OK, reopening to track documentation changes in the next update of Mini-XML...

**Comment by michaelrsweet** [comment]
OK, aside from additions to the function references, I've updated the intro text to talk about using opaque strings by default.
