### ISSUE TITLE
When I make this project ,There are errors.

### ISSUE THREAD

**Issue by huanghaoa** [michaelrsweet/mxml#191]
I download this project,and configure,make,there will be errors,like this
 mxmldoc.c:3981:37: error: ‘AE_IFREG’ undeclared (first use in this function)
   archive_entry_set_filetype(entry, AE_IFREG);
Did it lack the libarchive or something?

**Comment by greendow** [comment]
I compiled mini-XML 2.10 on 64-bit CentOS with GCC 4.4.7. No errors occurred.

**Comment by huanghaoa** [comment]
@greendow Thanks you,man.I mean I complied mini-xml code in the github now.Maybe I should wait for mini-XML 2.11.And mini-XML 2.10 had the memory leak in the mxmlNodeDelete,Author has fixed it in project now,look out.Forgive my English.

**Comment by greendow** [comment]
I also hope memory leak can be fixed in the next version. I used many open-source XML library developed with C, including mini-XML, libroxml, etc. Almost every one has memory leak problems more or less. Mini-XML does well and I hope it can go further.

**Comment by huanghaoa** [comment]
@greendow Author has fixed the memory leak. detail at https://github.com/michaelrsweet/mxml/commit/1272c3dfdb967f49ebb502f28ba3eb56e2360f54

**Comment by michaelrsweet** [comment]
Sorry, I pushed some changes to mxmldoc so that it can generate ePub books but haven't added all of the conditional code yet for systems without libarchive... it's coming...

**Comment by michaelrsweet** [comment]
The build issues should now be resolved.
