### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by A-Costa** [michaelrsweet/mxml#195]
the solution for the issue reported here: #183 
works on my macbook, but doesn't on the linux server i'm working on. 
maybe some strange non portable free call?

**Comment by michaelrsweet** [comment]
There isn't anything non-portable or OS-specific in that code. How are you checking for memory leaks?

**Comment by A-Costa** [comment]
I am really sorry. The problem was in my code. Unfortunately i'm working in a very unfriendly environment right now. 
closing!
