### ISSUE TITLE
Can't build.

### ISSUE THREAD

**Issue by MrSorcus** [michaelrsweet/mxml#197]
```
==> Starting build()...
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
host_os_version=0
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/sorcus/mxml/src/mxml':
configure: error: C compiler cannot create executables
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```
config.log - https://gist.github.com/MrSorcus/eaff21bbc650a1e4711c082a56428535
Linux vs0 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux

**Comment by michaelrsweet** [comment]
Looks like the configure script has not been regenerated, but otherwise the error you are getting indicates a bad or missing compiler. The config.log file shows the following error:

    /usr/bin/ld: cannot find -lgcc_s

which points to you missing one of the GCC support libraries...

**Comment by mario-schallner-m64** [comment]
Same error on ubuntu 64 bit. 
It's the configure script that can not deal with recent gcc versions. For example it tries to use the cmdline switch -V which is unknown to recent gcc:

./configure outputs:
mario@mbox:~/z/mxml$ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/mario/z/mxml':
configure: error: C compiler cannot create executables
See `config.log' for more details

config.log shows:
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
configure:2696: $? = 0
configure:2685: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2696: $? = 1
configure:2685: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:2696: $? = 1
configure:2716: checking whether the C compiler works
configure:2738: gcc    conftest.c  >&5
/usr/bin/x86_64-linux-gnu-ld: cannot find Scrt1.o: No such file or directory
/usr/bin/x86_64-linux-gnu-ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:2742: $? = 1
configure:2780: result: no
