### ISSUE TITLE
Make error: unable to find utility "docsetutil"

### ISSUE THREAD

**Issue by rceballos98** [michaelrsweet/mxml#198]
Hi, I'm trying to install this on a macbook pro 2015 with osx 10.11.6 following the instructions on the README.

Configuring works fine but I get the following error on make:

`| => make install
Compiling mxml-attr.c
Compiling mxml-entity.c
Compiling mxml-file.c
Compiling mxml-get.c
Compiling mxml-index.c
Compiling mxml-node.c
Compiling mxml-search.c
Compiling mxml-set.c
Compiling mxml-private.c
Compiling mxml-string.c
Creating libmxml.1.dylib...
Compiling mxmldoc.c
Compiling mmd.c
Compiling zipc.c
Linking mxmldoc...
Creating libmxml.a...
a - mxml-attr.o
a - mxml-entity.o
a - mxml-file.o
a - mxml-get.o
a - mxml-index.o
a - mxml-node.o
a - mxml-search.o
a - mxml-set.o
a - mxml-private.o
a - mxml-string.o
Compiling testmxml.c
Linking testmxml...
Testing library...
Stdio file test passed!
String test passed!
File descriptor test passed!
Linking mxmldoc-static...
Generating API documentation...
xcrun: error: unable to find utility "docsetutil", not a developer tool or in PATH
mxmldoc: docsetutil exited with status 72
xcrun: error: unable to find utility "docsetutil", not a developer tool or in PATH
make: *** [mxml.xml] Error 1`

I've tried configuring it both to /usr and /usr/local but I get the same error.
Any suggestions?

**Comment by michaelrsweet** [comment]
What version of Xcode do you have installed?

**Comment by rceballos98** [comment]
I uninstalled Xcode from my machine, I just have gcc.
Do I need Xcode to install this?

**Comment by michaelrsweet** [comment]
The current Mini-XML build system does assume you have Xcode on macOS simply because a) Xcode is free and b) without code signing tools you are extremely limited in what you can deploy.

I will investigate my options here, but support for Xcode documentation sets is a feature on macOS that I want to support.

**Comment by rceballos98** [comment]
Fair enough. Thank you for being so responsive btw.
I'll re-install Xcode and try again.

**Comment by jonnyzzz** [comment]
The `docsetutil` seems to be removed in XCode (not only in beta) 
https://github.com/tomaz/appledoc/issues/628

**Comment by jonnyzzz** [comment]
Is it possible to disable building the docs?

**Comment by michaelrsweet** [comment]
You’ll need to remove the build rule for now, I’ll put out an update without it... :/

**Comment by priyankamistry09** [comment]
I have tried with XCode 9.4.1 and it is giving the same issue.

**Comment by priyankamistry09** [comment]
I have tried with XCode 9.4.1 and it is giving the same issue.

**Comment by michaelrsweet** [comment]
OK, I've pulled docset support from the makefile, and will also be pulling it from mxmldoc shortly... :(

**Comment by michaelrsweet** [comment]
And now it is pulled from mxmldoc...
