### ISSUE TITLE
undefined reference to `strlcat'

### ISSUE THREAD

**Issue by spixi** [michaelrsweet/mxml#200]
When I want to build mxml with gcc-5.3.0, I get the following error:

>mxmldoc.o: In function \`write_epub':
>/mnt/hdd/home/username/mxml/mxmldoc.c:4397: undefined reference to \`strlcat'

This quick patch helps:

Implement strlcat in mxmldoc.c:

```
inline
size_t strlcat(char *dst, const char *src, size_t siz)
{
        size_t ld = strlen(dst);
        size_t ls = strlen(src);
        if (ld >= siz)
             return 0;
        if (ld + ls >= siz)
            ls = siz - ld -1;
        strncat(dst, src, ls);
        return ld + ls; 
}
```

**Comment by michaelrsweet** [comment]
This is already in libmxml - mxmldoc should be picking it up when it includes config.h...

What OS are you using?

**Comment by michaelrsweet** [comment]
OK, never mind I was able to reproduce on a current Ubuntu VM... Looks like we need to define _GNU_SOURCE as well as adding the strlcat emulation (just had strlcpy, my bad...)
