### ISSUE TITLE
Problem with MXML_CUSTOM in Version mxml-2.10

### ISSUE THREAD

**Issue by mkoennecke** [michaelrsweet/mxml#201]
Hi,

I am using the MXML_CUSTOM element together with custom callbacks for loading and writing. 
This all worked well for years but broke with version 2.10. I tracked it down to line 2928 of file mxml-file.c. In the distributed version the line reads:

    if ((data = (*global->custom_save_cb)(node)) == NULL)

but it must read:

    if ((data = (*global->custom_save_cb)(current)) == NULL)

With that change my code continued to work again. Please adopt my fix for version 2.11

**Comment by michaelrsweet** [comment]
[master ef7e5d4] Fix writing of custom data nodes (Issue #201)
