### ISSUE TITLE
How to add a new element then save it as ENCODE_UTF16BE encoding?

### ISSUE THREAD

**Issue by JohnWins** [michaelrsweet/mxml#203]
Hi,
I am a Newbie here and currently trying your library and it help a lot with pure C, but how can I add a new element and save xml file as ENCODE_UTF16BE encoding ?
I found that it use ENCODE_UTF8 by default, and read only without add or mod ?
Hope there are a lot of examples for a newbie who want to have a total view of so many pieces of code.

**Comment by michaelrsweet** [comment]
@JohnWins Mini-XML does not support writing of UTF-16 files or strings. I currently have no plans of enhancing Mini-XML to do so, sorry...
