### ISSUE TITLE
mxmlGetInteger

### ISSUE THREAD

**Issue by kallewirsch63** [michaelrsweet/mxml#204]
May I suggest an addition to mxmlGetInteger?
Something like this

int					/* O - Integer value or 0 */
mxmlGetInteger(mxml_node_t *node)	/* I - Node to get */
{
 /*
  * Range check input...
  */

  if (!node)
    return (0);

 /*
  * Return the integer value...
  */

  if (node->type == MXML_INTEGER)
    return (node->value.integer);
  else if (node->type == MXML_ELEMENT &&
           node->child &&
	   node->child->type == MXML_INTEGER)
    return (node->child->value.integer);

  else if(node->type == MXML_TEXT)
    return strtol(node->value.text.string, NULL, 10);

  else if (node->type == MXML_ELEMENT &&
      node->child &&
      node->child->type == MXML_TEXT)
    return strtol(node->child->value.text.string, NULL, 10);

  else
    return (0);
}

The issue is as follows:
When creating an XML Tree and inserting nodes via
mxmlNewInteger
all is fine. When stepping through the tree, the value can be get again by using mxmlGetInteger. But the situation changes, when the XML tree is stored to a file and loaded again. Since obviously there is no Integer Datatype in XML, the node value gets restored as a MXML_TEXT Node. And in this case, the original mxmlGetInteger will fail. This one would have to have 2 different cases, depending on how exactely the XML tree was created: during a program run or by loading it from a file.
Same for mxmlGetReal and mxmlNewReal.
By modifying the Get functions, this difference can be handled easily

**Comment by michaelrsweet** [comment]
But you can provide a load callback that tells Mini-XML what node type to use for child nodes (not just MXML_TEXT)...

**Comment by michaelrsweet** [comment]
(and I'm not comfortable making this kind of change because mxmlSetInteger would also need to be changed, which requires an MXML_INTEGER node...)
