### ISSUE TITLE
mxml_node_s link in documentation not working

### ISSUE THREAD

**Issue by kamalpandey1993** [michaelrsweet/mxml#205]
what is the definition of mxml_node_s 
the link in html page of documentation is not working for mxml_node_s
https://michaelrsweet.github.io/mxml/mxml.html#mxml_node_s
 this is the link.. please have a look or at least specify somewhere  the definition of mxml_node_s

**Comment by michaelrsweet** [comment]
The mxml_node_s structure is not meant to be public - there are accessor functions for each of the members of the structure.

(but of course you can always look at the code...)
