### ISSUE TITLE
Getting an Attribute Value 

### ISSUE THREAD

**Issue by dliving1518** [michaelrsweet/mxml#208]
I am attempting to use minixml to obtain the value of an attribute but it does not appear to work,  I have a simple XML test file test3.xml that I am attempting to extract an attribute value from. 

<?xml version="1.0" encoding="UTF-8"?>
<group>
      <g2sBody 
                dateTimeSent="2017-09-08T01:21:52Z" 
                egmId="ATI_B0321931" 
                hostId="1"> Hello
      </g2sBody>
</group>

I can do a a findPath ( mxmlFindPath(tree, "group/g2sBody") and it will find the element g2sBody, but mxmlElementGetAttr(node,"egmId")  will return a NULL value.   

Lookinng for some insight.

**Comment by michaelrsweet** [comment]
Can you attach the file you are trying to load?

**Comment by dliving1518** [comment]
Hello Michael,

commsOnline.xml is the one that I want to work with in the future.

I created test3.xml to see if I can get an attribute value.

mini-xml will find the element g2s:g2sBody by using xpath. If I try to get
the element name I get <null>

any quick advice?
thanks

**Comment by michaelrsweet** [comment]
Can you attach your test3.xml file to this issue? Kind of hard to provide any guidance without seeing what is going into Mini-XML...

**Comment by dliving1518** [comment]
I thought I had attached it...sorry

**Comment by dliving1518** [comment]
[test3.txt](https://github.com/michaelrsweet/mxml/files/1388451/test3.txt)

**Comment by michaelrsweet** [comment]
OK, simple fix: use "g2s:epmId" as the element name. Mini-XML does not support namespaces, so you need to use the full attribute name.

**Comment by dliving1518** [comment]
Sorry, I have been trying that and I simply get a <null> value.
here is my test code:

    if ((node = mxmlFindPath(tree, "group/g2s:g2sBody")) != NULL)
    {
      fputs(" Found g2s:g2sbody element in XML tree.\n", stderr);

    }
const char *attribute;
const char *egmId = "g2s:egmId";
attribute =  mxmlElementGetAttr (node, egmId);

printf ("attribute value is: %s \n", attribute);

RESULT
 Found g2s:g2sbody element in XML tree.
attribute value is: (null)
