### ISSUE TITLE
Memory leak in mxmlDelete

### ISSUE THREAD

**Issue by vvalentinich** [michaelrsweet/mxml#209]
It seems there is a memory leak in mxmlDelete. To reproduce the issue one can run a code like:
```
mxml_node_t*  tree = mxmlLoadString(NULL, "<?xml version=\"1.0\"?><Root><NT></NT></Root>", MXML_NO_CALLBACK);
mxmlDelete(tree);
```
Visual Studio will show a memory  leak. It seems replacing
```
else if ((next = temp->next) == NULL)
      {
	if ((next = temp->parent) == node)
	  next = NULL;
      }

```
with
```
else
				next = temp;

```
will resolve the leak.

**Comment by michaelrsweet** [comment]
What version of Mini-XML are you using? This sounds like issue #183 which was fixed a while back but not yet included in a release (I haven't had time to release v2.11 yet...)

**Comment by vvalentinich** [comment]
Yes, version 2.10. I am not an active user of GitHub, so closed issues was missed. Thanks.
