### ISSUE TITLE
libmxml.a: error adding symbols: File format not recognized

### ISSUE THREAD

**Issue by Pratikhyadav** [michaelrsweet/mxml#210]
When i am using compiled libxml.a on linux 64 bit . and use it in esp-idf. its says 
libmxml.a: error adding symbols: File format not recognized

**Comment by michaelrsweet** [comment]
What does "file libmxml.a" report?

**Comment by Pratikhyadav** [comment]
Thanks @michaelrsweet  , Solved it.

**Comment by deathholes** [comment]
@Pratikhyadav : how were you able to solve? I'm facing similar issue in some other library.
