### ISSUE TITLE
mxmlNewTextf error

### ISSUE THREAD

**Issue by bipbip59** [michaelrsweet/mxml#211]
Hello,
When a I make this code :
```
mxmlNewTextf(data1, 1, "%d",10);
```
I have an exception in 
_mxml_vstrdupf  function  (vsnprintf)

A juste make a change  to work good (add "&" to memcpy src).
```
#ifndef va_copy
#  ifdef __va_copy
#    define va_copy(dst,src) __va_copy(dst,src)
#  else
#    define va_copy(dst,src) memcpy(&dst, &src, sizeof(va_list))
#  endif /* __va_copy */
#endif /* va_copy */
```
bye

**Comment by michaelrsweet** [comment]
@bipbip59 What operating system? What compiler?

**Comment by bipbip59** [comment]
sorry, I use c++ builder XE7 (windows 8.1) but it's a console programm. I don't use WIN_32 define because 
this compiler don't have _vscprintf

**Comment by michaelrsweet** [comment]
(Reference original issue #184)

OK, that is not a compiler I currently support for Mini-XML. But it sounds like BCC has a similar problem as some versions of Visual Studio...

**Comment by michaelrsweet** [comment]
[master a90ff17] Update va_copy macro for BCC (Issue #211)
