### ISSUE TITLE
Parsing siblings

### ISSUE THREAD

**Issue by Opariti** [michaelrsweet/mxml#213]
I have problems to extract the siblings of a node, with both using the functions, as well as the node->prev and node->next properties. Do you have a simple working example on how to walk through the same level nodes, i.e. from a given node to find all its siblings?
I finely use the library with all other functionalities, but I'm bumping into this one.

**Comment by michaelrsweet** [comment]
@Opariti Sample code and data file, please?

**Comment by Opariti** [comment]
Thank you Michael.
I am calling the mxml1.dll functions (v. 2.11) in a C program in Visual Studio 2017. It always builds with no errors or warnings.
I need to create a function ('getNodeInfo' in code below) having as parameters an XML string tree (previously loaded from the file below) and a reference node. 
The function returns a string composed of concatenated info: node's parent name (section 'get parent node' in code below), siblings names (section 'get sibling nodes' in code below) and node's attributes (section 'get attributes' in code below).
Sections for 'parent' and 'attributes' are working fine.
To get the siblings of a node I start from the top of the tree and find all 'siblings': have the same parent as 'node', but different than 'node'. I need to do this way because I can have a node with siblings placed above it, to the top of the tree
Testing piecewise (comment/uncomment code) I've noted that, for the 'sibling' section I either have some wrong selections or not having access to the sibling variable name property (runtime exception, but not buffer size related).
Here is the function's code:

`char* getNodeInfo(mxml_node_t* node, mxml_node_t* tree) {
	mxml_node_t * parent = NULL;		// node's parent
	mxml_node_t * sibling = NULL;		// variable used to search for 'node' siblings

	char* resultString = (char*)malloc(TEMP_BUFFER_SIZE * sizeof(char));
	int n = strlen(resultString) * sizeof(char);

	strcpy_s(resultString, n, " #Node:");
	strcat_s(resultString, n, node->value.element.name);
	
	// get parent node
	parent = mxmlGetParent(node);
	strcat_s(resultString, n, " Parent= ");
	strcat_s(resultString, n, parent->value.element.name);
	strcat_s(resultString, n, "/");
	
	//get sibling nodes
	strcat_s(resultString, n, " Siblings= ");
	// get the parent's name
	char* parentName = parent->value.element.name;
	// parse the tree from top element to last element
	for (sibling = mxmlFindElement(tree, tree, NULL, NULL, NULL, MXML_DESCEND);
		sibling != NULL;
		sibling = mxmlWalkNext(sibling, tree, MXML_DESCEND)
		) {
		// validate the type of node under process
		if (sibling->type == MXML_ELEMENT) {
			// get the current iteration node's name
			char *siblingName = sibling->value.element.name;
			// select the 'sibling' if it has the same parent as 'node' and if it is different than 'node'
			if ((strcmp(parentName, siblingName) == 0)
				&& (node != sibling)) {
				strcat_s(resultString, n, siblingName);
                               //strcat_s(resultString, n, "siblingFound!");
			}
		}
	}	
	strcat_s(resultString, n, "/");

	// get attributes
	for (int k = 0; k < node->value.element.num_attrs; k++) {
		if (node->value.element.attrs) {
			//printf("Attribute Name :: %s \n", node->value.element.attrs[k].name);
			strcat_s(resultString, n, " Attr=");
			strcat_s(resultString, n, node->value.element.attrs[k].name);
			//printf("Attribute Value:: %s \n", node->value.element.attrs[k].value);
			strcat_s(resultString, n, " Attr-value=");
			strcat_s(resultString, n, node->value.element.attrs[k].value);
		}
	}
	
	resultString[strlen(resultString)] = '\0';
	return resultString;
}`
Here is the test file:

`<?xml version="1.0" encoding="UTF-8"?>
<x id="1" cmd="init" ses="aaaaaaa">
  <i>
    <test id="999" name="bbbbbbbb"/>
  </i>
  <j></j>
  <k></k>
</x>`

Thanks

**Comment by michaelrsweet** [comment]
Your test code is wrong - the second argument to strcat_s needs to be the size of the buffer, not the length of the string.

**Comment by Opariti** [comment]
Thanks Michael, indeed, and your parser works great!
