### ISSUE TITLE
Compile to have .a object

### ISSUE THREAD

**Issue by cecilmax** [michaelrsweet/mxml#214]
Hi, I would like to use the 2.11 version with github fceugx nes emulator project. How can I compile it to get mxml.a ? The source of fceugx need mxml.a and mxml.h for now it use mxml 2.6version..

**Comment by michaelrsweet** [comment]
By default you'll get both a static and shared (dynamic) library. With the configure script you can disable the shared library with "--disable-shared". The library name is "libmxml.a", however, NOT "mxml.a".
