### ISSUE TITLE
Log handler

### ISSUE THREAD

**Issue by topilski** [michaelrsweet/mxml#215]
Hi, i think it will be more flexible to have callback function for logs. For example in our project we using mxml library, and we wanna redirect mxml errors from stderr into our log file. For example here https://github.com/michaelrsweet/mxml/blob/master/mxml-node.c#L49 , it will be great to have global set_log_handler function, and call handler callback when some logs available.

**Comment by michaelrsweet** [comment]
Sounds reasonable, will look at this as part of the "big" 3.0 API changes.

**Comment by joede** [comment]
In the case you really implement this feature, think about using *log levels*.

Just as a inspiration... I'm using the following macros in my code. The pointer to the logging callback `cb_log` is never `NULL`. It either points to a user function or to a local default wrapping the `printf(stderr...)`.
~~~~
#define __CRITICAL(msg,args...) cb_log(DBG_LVL_CRIT,(msg),##args)
#define __ERROR(msg,args...)    cb_log(DBG_LVL_ERROR,(msg),##args)
#define __WARN(msg,args...)     cb_log(DBG_LVL_WARN,(msg),##args)
#define __NOTICE(msg,args...)   cb_log(DBG_LVL_NOTICE,(msg),##args)
#define __INFO(msg,args...)     cb_log(DBG_LVL_INFO,(msg),##args)
#define __DIAGNOSE(msg,args...) cb_log(DBG_LVL_DEBUG,(msg),##args)
#define __TRACE(msg,args...)    cb_log(DBG_LVL_DEBUG,(msg),##args)
#define __ASSERT(cond,msg,args...) do{if(cond){cb_log(DBG_LVL_CRIT,(msg),##args); return;}}while(0)
#define __ASSERT2(cond,msg,retval) do{if(cond){cb_log(DBG_LVL_CRIT,(msg),##args); return(retval);}}while(0)
#if defined(BETA) || defined(DEBUG)
# define __DEBUG(msg,args...)    cb_log(DBG_LVL_DEBUG,(msg),##args)
# define __DBGASSERT(cond,msg,args...) do{if(cond){cb_log(DBG_LVL_CRIT,(msg),##args); return;}}while(0)
# define __DBGASSERT2(cond,retval,msg,args...) do{if(cond){cb_log(DBG_LVL_CRIT,(msg),##args); return(retval);}}while(0)
#else
# define __DEBUG(msg,args...)
# define __DBGASSERT(cond,msg,args...)
# define __DBGASSERT2(cond,retval,msg,args...)
#endif
~~~~

**Comment by michaelrsweet** [comment]
Ugh. Just looking at this again and we already provide an error callback (default logs to stderr).

See the `mxmlSetErrorCallback` function...
