### ISSUE TITLE
mmxlLoad leaks nodes when the XML is not well-formed.

### ISSUE THREAD

**Issue by cluckhau** [michaelrsweet/mxml#217]
i have noticed that i have a memory leak in my application when using libmxml.
i was using version 2.10 and noticed the issue, went online and observed this was fixed in 2.11.
installed 2.11 and i still see the issue.

i have disabled all code but the following

FILE *fp;
fp = fopen("/tmp/xmlRecv1", "r");
if(!fp)return;
topTree = mxmlLoadFile(NULL, fp,MXML_OPAQUE_CALLBACK);
if(fp)fclose(fp);

mxmlDelete(topTree);

the xmlRec1 file is below.
[xmlRecv1.txt](https://github.com/michaelrsweet/mxml/files/1904543/xmlRecv1.txt)

any thoughts?

**Comment by michaelrsweet** [comment]
That's not a valid XML file...

Still, it shouldn't be leaking memory, and I'll take a look...

**Comment by cluckhau** [comment]
Thank you,

I run this loop every 200mS, in my example the XML file is the same.

**Comment by michaelrsweet** [comment]
If you create a dummy node and pass that as the parent node then it won't leak.

In the meantime, I'm still looking at this...

**Comment by michaelrsweet** [comment]
Hmm, well I cannot duplicate the issue with the current code - Valgrind comes up empty on memory leaks with your sample program and data file, and even hand tracing the code shows that there shouldn't be anything getting lost in the shuffle...

I'd re-confirm that you were linking against and using the latest libmxml...
