### ISSUE TITLE
autoheader failed with exit status: 1 during configure

### ISSUE THREAD

**Issue by MaxPayne86** [michaelrsweet/mxml#219]
Hi, I've written a [recipe](https://github.com/MaxPayne86/meta-moddevices/blob/master/recipes-sw/mxml/mxml.bb) for yocto for mxml package. I'm using it in a build for Raspberry Pi2. It fails during configure:

...
| DEBUG:   considering dependency: ['xz-native', 'do_populate_sysroot']
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: Executing shell function do_configure
| NOTE: Executing ACLOCAL="aclocal --system-acdir=/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/" autoreconf --verbose --install --force --exclude=autopoint -I /home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/
| ERROR: autoreconf execution failed.
| automake (GNU automake) 1.15
| Copyright (C) 2014 Free Software Foundation, Inc.
| License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
| This is free software: you are free to change and redistribute it.
| There is NO WARRANTY, to the extent permitted by law.
| 
| Written by Tom Tromey <tromey@redhat.com>
|        and Alexandre Duret-Lutz <adl@gnu.org>.
| AUTOV is 1
| autoreconf: Entering directory `.'
| autoreconf: configure.ac: not using Gettext
| autoreconf: running: aclocal --system-acdir=/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/ -I /home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/ --force
| autoreconf: configure.ac: tracing
| autoreconf: configure.ac: not using Libtool
| autoreconf: running: /home/softin/Work/RASP/build/tmp/sysroots/x86_64-linux/usr/bin/autoconf --include=/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/ --force
| autoreconf: running: /home/softin/Work/RASP/build/tmp/sysroots/x86_64-linux/usr/bin/autoheader --include=/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/mxml/2.11-r0/aclocal-copy/ --force
| autoheader: warning: missing template: HAVE_LONG_LONG
| autoheader: Use AC_DEFINE([HAVE_LONG_LONG], [], [Description])
| autoheader: warning: missing template: HAVE_PTHREAD_H
| autoheader: warning: missing template: HAVE_ZLIB_H
| autoheader: warning: missing template: MXML_VERSION
| autoreconf: /home/softin/Work/RASP/build/tmp/sysroots/x86_64-linux/usr/bin/autoheader failed with exit status: 1
...

I'm fetching 2.10.tar.gz, not sure what to do in order to solve this problem...seems related
to configure.ac file...

**Comment by michaelrsweet** [comment]
The configure script is already generated (so probably no need to regen), But if you are making changes just use autoconf to regenerate it. The rest of autotools is utter crap and will just cause problems here

**Comment by MaxPayne86** [comment]
Hi, I'm not making changes. I'm just trying to cross-compile this package fetching version 2.11 and I'm getting errors. Do you mean I don't have to use autotools? Why? It's used among hundreds of recipes in yocto...

**Comment by michaelrsweet** [comment]
Autotools is used to create the configure script,  config.h.in file, and make files. All this project uses is autoconf (a subset of autotools), and just like all projects using these tools the configure script is shipped pre-generated.

I’ve never heard of yocto, but there is no reason to run autotools to build a package from a released tarball.

**Comment by MaxPayne86** [comment]
Ok I will try to write my configure task instead of inheriting from standard yocto's autotools class, in theory should fix my problem, let's see. But please consider that would be nice if it could simply compile as is. Many linux packages just compile fine in yocto and the autotools class. For example [this](https://github.com/MaxPayne86/meta-moddevices/blob/master/recipes-sw/liblo/liblo_0.28.bb).
