### ISSUE TITLE
Save callback params insufficient for properly formatting document

### ISSUE THREAD

**Issue by LBensman** [michaelrsweet/mxml#220]
Save callback receives node and life-cycle event, but lacks any context for the node to determine how to pad whitespacing.  A workaround is to try to maintain own state through global variables (bad) and try to keep track of indentation, making it not thread-safe (and for MT application would require locking and performing all serializations sequentially affecting performance).  An opaque pointer that can be used to pass state around (or pass `this` pointer) would help resolve the issue.

Similarly, save document functions could be extended to perform automatic indentation formatting as optional functionality, taking in indentation specifier (i.e. tab, or set of characters, etc.).

**Comment by michaelrsweet** [comment]
The save callback has the current node, so from that you can determine a great deal of context from the parents, children, and siblings. Indentation can be achieved by counting the number of parents.

**Comment by michaelrsweet** [comment]
... and FWIW a future version of the API will likely have a context pointer - being tracked by issue #106.
