### ISSUE TITLE
Overriding `encoding` attribute on a processing instruction causes malformed document

### ISSUE THREAD

**Issue by LBensman** [michaelrsweet/mxml#221]
Unfortunately I no longer have the exact example of the affect of the issue, but it was resulting in errors in produced document.  The reason I needed to override `encoding` attribute of the processing instruction is because I needed value to be capitalized - `UTF-8` - as opposed to what mxml emits, which is `utf-8`.  I used the following code that resulted in malformed document:

```
    auto root = mxmlNewXML("1.0");
    mxmlElementSetAttr(root, "encoding", "UTF-8");
```

**Comment by michaelrsweet** [comment]
The root node is not a regular element, and the encoding attribute value is defined as case-insensitive - any XML parser that barfs on a lowercase "utf-8" is broken.

What you'll need to do is this:

    mxml_node_t *root = mxmlNewElement(NULL, "?xml version=\"1.0\" encoding=\"UTF-8\"?");

**Comment by LBensman** [comment]
Ah! I'll try the `mxmlNewElement` way, instead of editing serialized string with search-replace.

The reason for it arose from debugging and troubleshooting in tracing why xml message was being accepted from one source, but not another, and trying to eliminate any and all differences to narrow down the source of failure.  Indeed, I doubt it made a difference, but running compares made it a whole lot easier to read once diff tool stopped highlighting impertinent differences.
