### ISSUE TITLE
Arabic Text in built XML file

### ISSUE THREAD

**Issue by abougee** [michaelrsweet/mxml#225]
Hello,

I'm looking to build an XML file during application runtime that include elements encapsulating Arabic text.

I'm expecting results to be in this form:

<?xml version="1.0" encoding="UTF-8"?>
   <soapenv:Envelope 
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
      xmlns:init="http://raya.paymentplaform.com/gate/init">
      
      <English>Maadi</English>
      <Arabic>المعادي</Arabic>

   </soapenv:Envelope>

Instead, I'm getting this:
<?xml version="1.0" encoding="UTF-8"?>
   <soapenv:Envelope 
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
      xmlns:init="http://raya.paymentplaform.com/gate/init">
      
      <English>Maadi</English>
      <Arabic>Ø§ÙÙØ¹Ø§Ø¯Ù</Arabic>

   </soapenv:Envelope>

My approach is as follows:

	FILE* fp=NULL;
	mxml_node_t* pstBase=mxmlNewElement(MXML_NO_PARENT, "?xml\nversion=\"1.0\"\nencoding=\"UTF-8\"?");

	mxml_node_t* SoapEnvelope=mxmlNewElement(pstBase, "soapenv:Envelope");
	mxmlElementSetAttr(SoapEnvelope,"xmlns:soapenv","""http://schemas.xmlsoap.org/soap/envelope/""");
	mxmlElementSetAttr(SoapEnvelope,"xmlns:init","""http://raya.paymentplaform.com/gate/init""");

	mxml_node_t* English =  mxmlNewElement(SoapEnvelope,"English");
	mxmlNewText(English, 0, "Maadi");
	mxml_node_t* Arabic =  mxmlNewElement(SoapEnvelope,"Arabic");
	mxmlNewText(Arabic, 0,"المعادي");

	fp = fopen("text.xml", "w");
	mxmlSaveFile(pstBase, fp, MXML_TEXT_CALLBACK);
	fclose(fp);

Please Advise.

Regards,

Ahmed Abou-Ghanem
Senior POS Developer
Address:- 26th July St., Touristic Zone, 6th of October, 12568 Egypt
Mobile:- +20 100 0330 1680
http://www.rayacorp.com

**Comment by abougee** [comment]
Note: Arabic uses UTF-8 encoding.

**Comment by michaelrsweet** [comment]
This should just work as you expect it to, as Mini-XML reads and writes UTF-8.

What version of Mini-XML are you using?

**Comment by michaelrsweet** [comment]
OK, I'm not seeing this on my Mac - your test program correctly writes the Arabic text as expected.

Is your source code editor set to UTF-8?

**Comment by abougee** [comment]
Hello Michael.

Yes, the  source code editor's set to UTF-8 (It's eclipse Oxygen IDE). It
can read Arabic text from XML files, but writing Arabic text to XML via
this library is another issue. It doesn't work. It seems to write in the
file with a different encoding.

perhaps the problem happens when saving the XML file using mxmlsave().

**Comment by michaelrsweet** [comment]
The code does no transcoding - it just writes the raw bytes.
