### ISSUE TITLE
how to cross-compile the mxml？

### ISSUE THREAD

**Issue by leetoun** [michaelrsweet/mxml#229]
i want to cross-compile the mxml，cause i want to use libmxml on my board. i have a chip of iMX6DL .
is there some description or direction in the docs？

**Comment by fanr520** [comment]
./configure --prefix=/root/libxml/bin --enable-threads --host=arm-linux CC=/mcuzone/work/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-none-linux-gnueabi-gcc AR=/mcuzone/work/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-none-linux-gnueabi-ar

--prefix=install dir
--enable-threads  theads enabled
CC arm gcc path name
AR amr ar path name

**Comment by leetoun** [comment]
@fanr520  thank u very much。 i‘ve finished the cross-compile work。and i'll have a try with ur configuration。 best wishes for you！
