### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by fxcoudert** [michaelrsweet/mxml#231]
Hello,

The latest mxml release does not compile with Xcode 9.4 and Xcode 10, i.e. all latest Xcode versions for macOS from Sierra to Mojave. Could you please tag a new release, so that we can ship a working mxml in Homebrew (and surely other distros)?

Thanks

**Comment by michaelrsweet** [comment]
I'm working on it...  Just fixed the last of the crash bugs that were reported against 2.11 and am doing a bunch of testing now...
