### ISSUE TITLE
Add top level directory to release archive

### ISSUE THREAD

**Issue by paulmenzel** [michaelrsweet/mxml#242]
It is common to have a top folder in the release archive with the name `mxml-version`, like `mxml-2.12`. That way, extracting the archive without any option, won’t put the files in your current directory. If people do not want that, they can use the tar switch `--strip-components`.

**Comment by michaelrsweet** [comment]
Hmm, something weird going on with git archive... Investigating...

**Comment by michaelrsweet** [comment]
[master c07d6fc] Fix makesrcdist script's archive generation (Issue #242)

**Comment by michaelrsweet** [comment]
I also updated the 2.12 tarball...
