### ISSUE TITLE
_mxml_vstrdupf bug on Windows

### ISSUE THREAD

**Issue by ironxu** [michaelrsweet/mxml#245]
You should place parameter values instead of variables that return 256 bytes of gibberish.

= >

temp [256]. /* Small buffer for first vsnprintf */

If (bytes < sizeof (temp))
{
/ *
* Hey, the formatted string fits in the tiny buffer, so just dup that...
* /

Return (strdup (temp));
}

**The solution**
  if (bytes < sizeof(temp))
  {
	/*
	* Hey, the formatted string fits in the tiny buffer, so just dup that...
	*/
	  vsprintf_s(temp, 256, format, ap);
    return (strdup(temp));
  }

**Comment by michaelrsweet** [comment]
OK, so this is on Windows? Looks like the conditional code should be expanded so that the _vscprintf code immediately falls on the malloc and vsnprintf to the malloc'd buffer.

**Comment by michaelrsweet** [comment]
[master a69fcbc] Fix _mxml_vsnprintf on Windows (Issue #245)
