### ISSUE TITLE
[bug]mxmlSetTextA 

### ISSUE THREAD

**Issue by ironxu** [michaelrsweet/mxml#252]
root ＝ mxmlNewXML (“1.0”)
node_HwThemes ＝ mxmlNewElementA (root, “HwThemes”)

' // 桌面图标字体颜色
mxmlNewText (node_HwThemes, 0, “”)
node_color ＝ mxmlNewElement (node_HwThemes, “color”)
mxmlElementSetAttr (node_color, “name”, “workspace_app_text_color”)
mxmlSetText (node_color, 0, “#FFFFFFFF”)

mxmlRelease (root)

### **As a result,
&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;HwThemes&gt;&lt;!-- 桌面图标字体颜色 --&gt;&lt;color
name="workspace_app_text_color" /&gt;&lt;/HwThemes&gt;**

### **It should be**

**&lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;HwThemes&gt;&lt;!-- 桌面图标字体颜色 --&gt;&lt;color
name="workspace_app_text_color" /&gt;#FFFFFFFF&lt;/HwThemes&gt;**

and **Why mxmlElementSetAttr is '\r' and not " "**

**Comment by michaelrsweet** [comment]
@ironxu What version of Mini-XML are you using?

As for the whitespace separator between attributes in an element, that is likely the wrap margin used when saving the document - see the `mxmlSetWrapMargin` function, the default margin is 75 columns.
