### ISSUE TITLE
Does it support pretty-print now?

### ISSUE THREAD

**Issue by ironxu** [michaelrsweet/mxml#253]
Does it support pretty-print now?
If so, what do I need to do?

**Comment by imdevcx** [comment]
```
const char *
xml_fmt_cb(mxml_node_t *node, int w)
{
    mxml_node_t *parent = mxmlGetParent(node);
    if (parent == NULL) {
        // first line
        return w == MXML_WS_AFTER_CLOSE ? EOXE : NULL;
    }
    else if (mxmlGetParent(parent) == NULL && w == MXML_WS_BEFORE_CLOSE) {
        // root element
        return EOXE;
    }

    int lv = 0;
    while ((parent = mxmlGetParent(parent))) {
        lv++;
    }

    if (w == MXML_WS_BEFORE_OPEN) {
        char tmp[1024] = {0};
        sprintf(tmp, EOXE "%*s", lv * 4, "");
        const char *ret = tmp;
        return ret;
    }

    return NULL;
}

mxmlSaveAllocString(node, xml_fmt_cb);
```

**Comment by cxstdio** [comment]
v2.0

const char *
xml_fmt_cb(mxml_node_t *node, int w)
{
    char sp[1024] = {0};
    int deep = 0;
    mxml_node_t *child, *parent;

    parent = mxmlGetParent(node);
    while ((parent = mxmlGetParent(parent))) deep++;
    sprintf(sp, "%*s", deep * 4, "");

    switch (w) {
        case MXML_WS_BEFORE_OPEN:
            break;
        
        case MXML_WS_AFTER_OPEN:
            child = mxmlGetFirstChild(node);
            while (child && mxmlGetType(child) != MXML_ELEMENT) {
                child = mxmlWalkNext(child, node, MXML_NO_DESCEND);
            }
            return child == NULL ? NULL : EOXE;

        case MXML_WS_BEFORE_CLOSE:
            child = mxmlGetFirstChild(node);
            while (child && mxmlGetType(child) != MXML_ELEMENT) {
                child = mxmlWalkNext(child, node, MXML_NO_DESCEND);
            }
            if (child) {
                break;
            }
            return NULL;

        case MXML_WS_AFTER_CLOSE:
            return EOXE;

        default:
            return NULL;
    }
    const char *ret = sp;

    return ret;
}
