### ISSUE TITLE
Got 'implicit function declaration' warning

### ISSUE THREAD

**Issue by tfarina** [michaelrsweet/mxml#254]
../mxml-string.c:98:7: warning: implicit declaration of function 'vasprintf' is invalid in C99 [-Wimplicit-function-declaration]
  if (vasprintf(&s, format, ap) < 0)

**Comment by michaelrsweet** [comment]
@tfarina What OS and compiler are you using?

**Comment by tfarina** [comment]
Ubuntu clang version 3.5.2-3ubuntu1

**Comment by michaelrsweet** [comment]
@tfarina Hmm, I can't reproduce. Can you attach the configure command you used and the output from "make"?

**Comment by tfarina** [comment]
Apologizes. This was in my CMake build. autotools build (configure + make) does not issue this warning. I must be missing something in my cmake build file.
