### ISSUE TITLE
base64 text confuses parser and generates error

### ISSUE THREAD

**Issue by alsaleem00** [michaelrsweet/mxml#255]
I am decoding an xml text that contains base64 encoded binary using mxmlLoadString. A sample text is shown below.

`<tas><cmd>48</cmd><id>000173</id><templ>TlQAEGcCAAAKAU5GVBBdAgAACgFORlImUwIZAAFoAfQB9AEAAP53AQEAAAAAB/4dB/2hgA0nB3dy1SAOMAtw50rhBT0FcfZpgQw8CGZrfYEKRAZw67IBB0MEbmfNgQNKAXHy/iEJRglo/6qiD1AGY4OuohNOCWpu0UILTwhvC/1iE1EKaX+NgxFNC3QToaMcLw5kE7oDFFEJb2P1gw80FXYmBcQaTQ5jTw2kBU8LbU1ZJAs/D3dZboQRMVFxMJGEEjs0eEGhJBE1PYBHrYQEUwdzQcEEDUsKhDTBBBpNBnA++gQYUgp2TB3FFUoMgrc1JRQ8GYmwYUUTMR6JBlwB/wHyAwJB/////////wDy/////wn6AwQzAwQzBQYi/////////wj3CgSBAv8/Af8/BQIT/wHzAwkXCAdyBAcSCv9/Bv8fAgEi/////wLyBQcTEf/P/wj0Cv9fBgUyBAMiCQwVDwqBBwNH////BwNH////DQ71Cwgh/wb4B/9fCAwVDxGEDQ70DApCCAki/////wj1C/9PDhQWDxIz/xj/EA7/C///////GBMkDxEkDAsU/xDxEv8fCgyDDhkiExcyGBk0FA5xCQ1v/////////wf5Cg9FEhZR/xb1EQpYDxMUF/8/FxIkDw40EBliFBURG/8fFRMxDhBXGBpS/xf0Eg9lExQTGhtT/////wb9ERIVHP/f////FhKDDxUkG/9//xnyFA5SEP8//////xryFA4yEBhC////HBsyFA4kGBlS////DhpS/////xzyFxRxFRsS////////FhfVAQQ1jSQRAAcABAAA</templ><len>820</len></tas>`

I verified the xml using online tools, but I am getting 

`mxml: Mismatched close tag </templ> under parent <(null)> on line 1.`

Is there an escape to do for base64 ?

Thanks.

**Comment by michaelrsweet** [comment]
@alsaleem00 There isn't anything you need to do to handle Base64 content, but you *do* need to use valid XML - without the `<?xml ...?>`, mxmlLoadString needs you to provide a root node (passed in the "top" argument).

(*maybe I should update the mxmlLoad functions to look for ?xml if top is NULL?*)

**Comment by alsaleem00** [comment]
given the text above and function call below:
mxmlLoadString(NULL, rxBuf, MXML_NO_CALLBACK)

should I call like this ("<tas>", rxBuf, MXML_NO_CALLBACK); ?

thanks.

**Comment by alsaleem00** [comment]
Sorry, I closed mistakingly.

**Comment by michaelrsweet** [comment]
No, use:

    mxml_node_t *xml = mxmlNewXML("1.0");
    mxml_node_t *tas = mxmlLoadString(xml, rxBuf, MXML_NO_CALLBACK);

**Comment by alsaleem00** [comment]
Thanks.

**Comment by alsaleem00** [comment]
Just to clarify the cause of the problem :
The problem was caused by not clearing the memory allocated by "malloc".
The previous packet to this packet was longer than this one. Memory manager happened to allocate same memory location, thus this packet had two ending tags, since "malloc" does not clear the memory it allocated, one from this packet and the other is from previous packet thatcaused the error.
I assumed that mxml will stop when finds the closing tag of the root tag, but it did not.

My problem solved when clearing the memory allocated by malloc.

Thanks for the help.
