### ISSUE TITLE
The final xml file does not have new lines

### ISSUE THREAD

**Issue by akmubi** [michaelrsweet/mxml#263]
I don't know why but xml file doesn't contain any new lines at all.  Is that Ok? Maybe it's normal. 
Example:
`<?xml version="1.0" encoding="utf-8"?><Id>0</Id><Question>node 0</Question><Answer>ans 1<Id>1</Id><Question>node 1</Question></Answer>
`

**Comment by michaelrsweet** [comment]
Without a save callback, Mini-XML will not insert any newlines or whitespace since it can affect the data when it is read back.
