### ISSUE TITLE
Unquoted attribute values which start with a multibyte character aren't recovered correctly.

### ISSUE THREAD

**Issue by eeepsylon** [michaelrsweet/mxml#264]
If the first character of an **unquoted** attribute is a multi-byte character, only the last byte of the codepoint value appears to be transferred to the entity value.

`<?xml version="1.0" encoding="utf-8"?><item cost=€100 />`

```
mxml_file_getc: ▒ (0x20ac)
mxml_file_getc: 1 (0x0031)
mxml_file_getc: 0 (0x0030)
mxml_file_getc: 0 (0x0030)
mxml_file_getc:   (0x0020)
mxmlElementSetAttr(node=0x11dfe00, name="cost", value="▒100")
```
In mxml-file.c: mxml_parse_element(), instead of: 
```
       /*
        * Read unquoted value...
	*/
	value[0] = ch;
	ptr      = value + 1;
```
use mxml_add_char():
```	
	ptr = value;
	if (mxml_add_char(ch, &ptr, &value, &valsize))
	  goto error;
```

Kindest Regards!

**Comment by michaelrsweet** [comment]
[master 2099ff6] Fix unquoted Unicode attribute values (Issue #264)
