### ISSUE TITLE
mxml-private.h and config.h should be included

### ISSUE THREAD

**Issue by Jim-CodeHub** [michaelrsweet/mxml#265]
single header file mxml.h can not pass compile (for version 3.1)

**Comment by michaelrsweet** [comment]
@Jim-CodeHub What do you mean?

Neither config.h nor mxml-private.h are public API header files meant for use outside of the Mini-XML sources. If you are trying to access the mxml_node_t members directly, that structure was made private in Mini-XML 3.0 in order to allow for future changes.
