### ISSUE TITLE
mxmlLoadString - what if XML is not well-formed

### ISSUE THREAD

**Issue by damaxi** [michaelrsweet/mxml#266]
According to specification:
> If no top node is provided, the XML string MUST be well-formed with a single parent node like <?xml> for the entire string.

What happens in the case when we provide not well-formed XML string with NULL parent node?
Is it undefined behavior?

**Comment by michaelrsweet** [comment]
Generally you'll get an error and nothing will be loaded. Previously you'd get the first node and nothing else (plus a memory leak).

**Comment by damaxi** [comment]
@michaelrsweet I tried the following code and it still prints:
```c 
mxml_node_t *xml = mxmlLoadString(NULL, "<initiator><node1>msg</node1><node2>msg2</node2></initiator>",
                  MXML_TEXT_CALLBACK);
  char* str = mxmlSaveAllocString(xml, MXML_NO_CALLBACK);
  puts(str);
  free(str);
  mxmlDelete(xml);
````
Output:
`<initiator><node1>msg</node1><node2>msg2</node2></initiator>`

**Comment by michaelrsweet** [comment]
The code is relaxed enough to allow any single top-level node (not just "?xml"), but the documentation warning is there because there is a lot of bad XML being passed around and I don't want to encourage that... :)
