### ISSUE TITLE
Attribute names (incorrectly) cannot start with a Unicode character

### ISSUE THREAD

**Issue by Yurgis57** [michaelrsweet/mxml#267]
Hi!
While parsing the XML file, If the first character of unquoted Attribute name is not Ansi-127, it is replaced with 1-byte code and is not converted to Utf properly. The rest characters are OK. Element names are OK too.
The effect exists from early mxml versions up to now.
Could you please replace just 2 lines in minixml-3.1 -> mxml-file.c -> mxml_parse_element:
    name[0] = ch;         (line 2191)
    ptr     = name + 1;  (line 2192)
with something like that:
	ptr = name;
	if (mxml_add_char(ch, &ptr, &name, &namesize))
	  goto error;

**Comment by michaelrsweet** [comment]
Will incorporate this fix into the next Mini-XML release.

**Comment by Yurgis57** [comment]
Thanks a lot

George Razutov
  ----- Original Message -----

**Comment by michaelrsweet** [comment]
[master dd55272] Fix handling of elements that start with a Unicode character (Issue #267)
