### ISSUE TITLE
you can write a xmake.lua

### ISSUE THREAD

**Issue by wujilingfeng** [michaelrsweet/mxml#280]
Hello!
Xmake is a lightweight cross-platform build utility based on Lua.It's so simple , clear and almighty.
If you have no time, you can give me  some compilation requirements . I will provide a xmake fiile.

Maybe you just need describe your demands clearly and tell me the file dependencies.

This is my mailbox: lishifucun@gmail.com
Xmake will be helpful to compile this libary on cross platform.

**Comment by michaelrsweet** [comment]
Thanks, but right now I am happy with my current build system.

**Comment by wujilingfeng** [comment]
OK.
What this sentensce "#define inline _inline" means? I didn't find such usage.

**Comment by michaelrsweet** [comment]
@wujilingfeng The `#define inline` line is used to replace "inline" with "_inline" or "" (nothing) depending on what keyword the current C compiler uses to specify an inline function.
