### ISSUE TITLE
The tag 'v3.2' is not on the master branch

### ISSUE THREAD

**Issue by texierp** [michaelrsweet/mxml#283]
Hi @michaelrsweet,

It seems that the tag `v3.2` is missing on master branch, see [1]:

```
26fb9e0 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #282 from orbea/libtool
4e2e312 build: Don't use libtool.
ab78fd8 Add Liberapay to Mini-XML funding options.
23dddcf Bump version.
5490479 Merge pull request #274 from timgates42/bugfix_typo_destination
38a533c docs: fix simple typo, destinatipon -> destination
dd55272 Fix handling of elements that start with a Unicode character (Issue #267)
f1b2682 Clean up .gitignore and Makefile cleaning up of temporary files.
371bb0c Bump copyrights.
f245429 I am beginning to dislike lawyers. (Issue #270)
fd5cfe4 Create FUNDING.yml
b43af67 Update documentation.
2099ff6 Fix unquoted Unicode attribute values (Issue #264)
12a8d29 Fix typo in changelog.
8b84490 Add support for shared libraries on the Haiku OS (Issue #262)
cccb6ea Add header guard.
55c6c72 Add proper annotation to mxml_error and fix format string errors in several places (detected by LGTM security scanner)
e483e5f (tag: v3.1) Bump minor version in header.
f2cbb0f Update README.
e2f7978 Roll back part of the change for Issue #256 since it causes a regression for some applications and the XML 1.0 specification only requires an XML file to start with '<' (Issue #259)
03ed2dd Change log.
a084198 Error out when file does not start with ?xml and the top node is NULL (Issue #256)
aec92c4 Update ignored files.
75da0dc Fix make install issues (Issue #257)
c7755b6 (tag: v3.0) Fix HTML link to cover image.
...
```

Is it possible to push it ? :)

Thanks

../Pierre-Jean

[1] - https://github.com/michaelrsweet/mxml/commit/38b044ed8ca2a611ed9ed3e26c4b46416335194e

**Comment by michaelrsweet** [comment]
Looking at the Github list of tags, I see v3.2 at the top. And in my local copy I see:

```
git tag | grep 3.2
v3.2
```

**Comment by texierp** [comment]
Yes you're right, but I don't know why it seems missing on master (e.g git log - - oneline) :/

**Comment by michaelrsweet** [comment]
Probably because I haven't committed any more changes after the tag...

**Comment by texierp** [comment]
But this commit https://github.com/michaelrsweet/mxml/commit/38b044ed8ca2a611ed9ed3e26c4b46416335194e is missing on master

**Comment by texierp** [comment]
In fact,the real problem is about the maintenance. If I try to upgrade the package that we have in openembedded side [1], I have the following issue:

```
Sstate summary: Wanted 0 Local 0 Network 0 Missed 0 Current 20 (0% match, 100% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 93 tasks of which 90 didn't need to be rerun and all succeeded.
INFO: Extracting upgraded version source...
ERROR: Execution of 'git checkout 38b044ed8ca2a611ed9ed3e26c4b46416335194e' failed with exit code 128:
fatal: reference is not a tree: 38b044ed8ca2a611ed9ed3e26c4b46416335194e
```

Normal because the commit  38b044ed8ca2a611ed9ed3e26c4b46416335194e (the reference for the version 3.2)  is not on master or at least not on a specific branch ...

**Comment by michaelrsweet** [comment]
@texierp I have no idea what went wrong with this tagging that you don't see the tag on master. All of my releases are automated with a script so I don't screw it up... :) I will investigate further on my other machines in case something from a local clone wasn't pushed, but since Github sees the tag I'm not sure that will yield anything.

For your OpenEmbedded recipe you should be pointing at the signed tarballs I post for every release and not pulling a Git revision, since the exported tarballs omit Git-specific source files that are not part of a normal release.
