### ISSUE TITLE
MXML_MINOR_VERSION is still set to 1

### ISSUE THREAD

**Issue by mattiagaruti-cima** [michaelrsweet/mxml#285]
Hi,
I just noticed that the minor version define is still set to 1 instead of 2.
Regards

**Comment by michaelrsweet** [comment]
Oops, fixed:

[master c44aa25] Fix minor version in header (Issue #285)

**Comment by LBensman** [comment]
@michaelrsweet , it is again out of sync.  Per CHANGES.md's latest entry [# Changes in Mini-XML 3.3.2](https://github.com/michaelrsweet/mxml/blob/809204a3051607f54b57e2950f3a5520d79ae383/CHANGES.md#L1-L2), the most current version is `3.3.2` whereas .h file still reflects it as `3.2`.

In fact, it's kinda a bit funny how this issue's fix of updating it to 3.2 is referenced as fix [released in 3.3 release](https://github.com/michaelrsweet/mxml/blob/809204a3051607f54b57e2950f3a5520d79ae383/CHANGES.md#L18-L19) 😆, making it already outdated on release.
