### ISSUE TITLE
Take xml loaded into a string and convert it back into regular xml format

### ISSUE THREAD

**Issue by akorb1** [michaelrsweet/mxml#289]
When a tree is created with newly created xml and then saved as a string, I would something to be able to take it out of string format and put it back into normal xml format for printing purposes.

**Comment by michaelrsweet** [comment]
@akorb1 If you want pretty-formatted XML, use a [save callback to insert whitespace](https://www.msweet.org/mxml/mxml.html#saving-an-xml-file).
