### ISSUE TITLE
Simplified file loading option?

### ISSUE THREAD

**Issue by bucanero** [michaelrsweet/mxml#291]
Hi,

Could we add another loading option that takes a file path string and returns the XML tree?

Something like:
```c
mxml_node_t *tree;

tree = mxmlLoadFilePath(NULL, "/path/to/filename.xml", MXML_OPAQUE_CALLBACK);
```

I know it's a trivial wrapper on `mxmlLoadFile()` but I think it could be useful for new users.

**Comment by michaelrsweet** [comment]
Added in latest Git master.
