### ISSUE TITLE
how to cross compile MXML for  STM32 MCU?

### ISSUE THREAD

**Issue by tyrael-cui** [michaelrsweet/mxml#292]
hi ,i want to use MXML in a board based on STM32 MCU without linux. Is there a way to cross comile MXML for this ? 
Thanks for any help!

**Comment by michaelrsweet** [comment]
The configure script supports the usual GNU cross-compilation options (`--host=xxx` and `--build=xxx`). Beyond that you'd need to set the `CC` and `AR` environment variables to point to your cross-compiler and cross-archiver programs.
