### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by robinqhuang** [michaelrsweet/mxml#295]
hi there,

how to fix the configure error?

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a BSD-compatible install... /bin/install -c
checking for ranlib... ranlib
checking for ar... ar
checking for cp... /bin/cp
checking for ldconfig... /sbin/ldconfig
checking for ln... /bin/ln
checking for mkdir... /bin/mkdir
checking for rm... /bin/rm
checking for inline... inline
checking for strdup... yes
checking for strlcat... no
checking for strlcpy... no
checking for snprintf... yes
checking for vasprintf... yes
checking for vsnprintf... yes
checking for unsigned long long int... yes
checking for long long int... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for pthread.h... yes
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
checking for shared library support... yes
checking whether compiler supports -Wno-char-subscripts... yes
checking whether compiler supports -Wno-format-truncation... yes
checking whether compiler supports -Wno-format-y2k... yes
checking whether compiler supports -Wno-switch... yes
checking whether compiler supports -Wno-unused-result... yes
configure: creating ./config.status
./config.status: line 527: 0a1,76: command not found
./config.status: line 528: syntax error near unexpected token `newline'
./config.status: line 528: `> # This file is a shell script that caches the results of configure'

**Comment by michaelrsweet** [comment]
@robinqhuang I can't reproduce.

What platform are you running on?

Are you configuring the Git sources or did you download a tarball?

What version?

**Comment by robinqhuang** [comment]
It is a customized "linux" platform. other libs are built successfully.
I downloaded mxml-3.3.tar.gz

**Comment by michaelrsweet** [comment]
OK, I just downloaded the release tarball and ran the configure script with no errors.
