### ISSUE TITLE
Build static library?

### ISSUE THREAD

**Issue by wusspuss** [michaelrsweet/mxml#308]
How can I build a static library, `.a`? I don't see an option for static linking in `configure --help`

**Comment by michaelrsweet** [comment]
From the `configure --help` output:

```
  --disable-shared        turn off shared libraries, default=no
```

Using this option creates and installs libmxml.a instead of the corresponding shared library. Also, building the testmxml program also forces building libmxml.a, although it won't be installed without using `--disable-shared`.
