### ISSUE TITLE
MXML_MINOR_VERSION is still set to 2

### ISSUE THREAD

**Issue by LBensman** [michaelrsweet/mxml#310]
I [already noted it](https://github.com/michaelrsweet/mxml/issues/285#issuecomment-1965533494) on a similar, but old and closed issue, but I figured it's probably best to note it on a brand new, open issue to make sure it's seen.

`MXML_MINOR_VERSION` is again out of sync. Per CHANGES.md's latest entry [# Changes in Mini-XML 3.3.2](https://github.com/michaelrsweet/mxml/blob/809204a3051607f54b57e2950f3a5520d79ae383/CHANGES.md#L1-L2), the most current version is 3.3.2 whereas .h file still reflects it as 3.2.

In fact, it's kinda a bit funny how this issue's fix of updating it to 3.2 is referenced as fix [released in 3.3 release](https://github.com/michaelrsweet/mxml/blob/809204a3051607f54b57e2950f3a5520d79ae383/CHANGES.md#L18-L19) 😆, making it already outdated on that release 😂.

**Comment by michaelrsweet** [comment]
and this is fixed in master for 4.0. Not doing another 3.x release.
