### ISSUE TITLE
Parallel installation of mxml-3 and mxml-4 fails because of man page

### ISSUE THREAD

**Issue by ConiKost** [michaelrsweet/mxml#324]
Hello michael,
I am the maintainer of mxml in Gentoo Linux.

Currently, we have version 3.x in our tree and I would like to add version 4.x too. As I understand, this is not a simple update, since new version is not API compatible with 3.x.

For such, we have slotting, so multiple variants of the package could be installed. This means, that mxml-3 and mxml-4 could be installed at the same time. From the changelog, it should be doable with ```--enable-libmxml4-prefix```.

The problem is, that both installations, mxml3 and mxml4, install the same file for man page:
``` Detected file collision(s): /usr/share/man/man3/mxml.3.xz ```
This message comes from Gentoo, which automatically detects duplicate files, which were already installed by mxml3 and mxml4 tries now to install.

Could be this somehow separated, that mxml4 will use a different name here?

Since the lib is anyway being installed as mxml4, it could make sense to rename the man page too?

```
--- /usr/
--- /usr/include/
>>> /usr/include/libmxml4/
>>> /usr/include/libmxml4/mxml.h
--- /usr/share/
--- /usr/share/man/
--- /usr/share/man/man3/
>>> /usr/share/man/man3/mxml4.3.xz
--- /usr/share/doc/
>>> /usr/share/doc/mxml-4.0.2/
>>> /usr/share/doc/mxml-4.0.2/NOTICE.xz
>>> /usr/share/doc/mxml-4.0.2/LICENSE.xz
>>> /usr/share/doc/mxml-4.0.2/mxml.epub.xz
>>> /usr/share/doc/mxml-4.0.2/CHANGES.xz
>>> /usr/share/doc/mxml-4.0.2/README.xz
>>> /usr/share/doc/mxml-4.0.2/mxml-cover.png
>>> /usr/share/doc/mxml-4.0.2/mxml.html
--- /usr/lib64/
--- /usr/lib64/pkgconfig/
>>> /usr/lib64/pkgconfig/mxml4.pc
>>> /usr/lib64/libmxml4.a
>>> /usr/lib64/libmxml4.so.2
>>> /usr/lib64/libmxml4.so -> libmxml4.so.2
```

Thank you!

**Comment by michaelrsweet** [comment]
Oops, yes I'll install as mxml4.3 when the prefix is being used.

**Comment by michaelrsweet** [comment]
[master c81526a] Install mxml man page as mxml4 by default (Issue #324)
