### ISSUE TITLE
MXML_NO_PARENT is documented but is not defined

### ISSUE THREAD

**Issue by chad-earthscope** [michaelrsweet/mxml#334]
The `MXML_NO_PARENT` value is documented as an input value for many functions, e.g. https://www.msweet.org/mxml/mxml.html#mxmlNewElement

but is not set anywhere in v4.0.3 (that I can find).

In v3.3.1 for example this was defined in mxml.h:
```
#  define MXML_NO_PARENT        0       /* No parent for the node */
```

So I'm using `NULL` with `mxmlNewElement()` instead, which appears to work as desired.

**Comment by michaelrsweet** [comment]
OK, that's a holdover from Mini-XML 3.x, and using NULL is the correct approach.

**Comment by michaelrsweet** [comment]
[master 61eddf1] Update docos (Issue #334)
