### ISSUE TITLE
HAVE_LONG_LONG_INT defined but not used

### ISSUE THREAD

**Issue by chad-earthscope** [michaelrsweet/mxml#335]
In my use case I need very few configuration options, only `--disable-shared --enable-threads`.  The resulting config.h only contains:
```
#  define MXML_VERSION "Mini-XML v4.0.3"
#  define HAVE_LONG_LONG_INT 1
#  define HAVE_PTHREAD_H 1
```

The `HAVE_LONG_LONG_INT` is not used in the code.

It would be useful to be able to set configuration options via compiler command line defines, in my case just for threading support, and to avoid needing autoconf/configure completely for what I suspect are many use cases.  

autoconf is kinda slow, but more importantly can be finicky on end users systems, especially after going through systems like git that change file modification times. This seems very close to being unnecessary (for my case and I suspect others).

Also, thank you very much for this library.  I have been relying on Mini-XML for ~14 years!

**Comment by michaelrsweet** [comment]
[master 2741eca] Drop long long config tests (Issue #335)

**Comment by michaelrsweet** [comment]
OK, so short of adding a "linux" subdirectory with a makefile and config script, I don't see dumping autoconf. The config.h file *is* short for Mini-XML, but the configure script also determines how (and whether) to make shared/static libraries, where to install things, etc.

**Comment by chad-earthscope** [comment]
Thanks @michaelrsweet.  My feature request was not to dump autoconf, but to provide an alternative that does not require creating your own config.h or Makefile (which is exactly what I'm doing now), which would make Mini-XML even easier to use and integrate into projects.

For example, an approach where:
1) a Makefile is provided in the distribution that will build with the default options, and will be replaced if `configure` is run.
and
2) `config.h` is optional (or the inclusion can be disabled)
and
3) the options were all settable as defines  (which I think is true now),
would allow integration that is as simple as untarring the release and running `make` with `CFLAGS` set as you wish.  This also leaves the capability for folks to run `configure` can tweak options for more advanced configuration.

In my case I want to set something like `CFLAGS += -DMXML_PTHREADS` and run `make` and get a static library.  Of course, I can make the extra config.h and/or Makefiles, but that adds overhead and more care is needed when updating to newer versions.  Merely a suggestion to lower the, admittedly already low, bar for use.

**Comment by michaelrsweet** [comment]
[master 880a461] Add linux makefiles (Issue #335)
