### ISSUE TITLE
Stop SAX parsing from callback

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#51]
Version: 3.x-feature
Original reporter: Michael Sweet

In a project i'm currently working on we have xml-files of several MB's. As i don't want to read the whole document in memory i will use the new SAX API. From this document i only want to read the attributes of the rootnode.

It would be nice if we could stop the stream parsing if we have found what we were looking for. So we don't need to read through the whole document.

**Comment by michaelrsweet** [comment]
OK, I'm scoping the changes that will land in Mini-XML 3.0 and I think I will be holding off on breaking API changes for now, sorry...

**Comment by GPaso** [comment]
I am working on a C project in which this feature could be very useful, but you say that the patch will break retro-compatibility?

**Comment by michaelrsweet** [comment]
@GPaso Yes because changing the SAX callback function to return a value (right now it is a void function) will break existing users of the API.

**Comment by michaelrsweet** [comment]
[master 3df751f] SAX callback now returns a boolean (Issue #51)
