### ISSUE TITLE
Extra whitespace calls on Empty Tag

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#55]
Version: 2.3
Original reporter: Michael Sweet

I've written a generic whitespace callback function to indent the tags of the xml file without using the name of the tag.

The only problem i had was with a node with empty tags. For those tags the MXML_WS_BEFORE_CLOSE and the MXML_WS_AFTER_CLOSE aren't called. Adding those calls fixed my generic callback. Maybe it can also be added to the library. Empty tags are a short notation of an open tag and an end tag. In my opinion the close calls should also be done on an empty tag.

**Comment by adaerr** [comment]
I agree with the original remark that 

> "Empty tags are a short notation of an open tag and an end tag. In my opinion the close calls should also be done on an empty tag.

Semantically a `<node />`, being shorthand for `<node></node>`, should IMHO trigger a `WS_BEFORE_OPEN` and `WS_AFTER_CLOSE` callback, but nothing in
between.

Thanks for suggesting as a workaround, equating `(MSML_WS_AFTER_OPEN
&& (node->child==NULL))` with `AFTER_CLOSE` for this kind of node.

I understand that changing the callback events now may change the
output of existing apps, but unless those apps have hijacked that
callback for injection of things other than whitespace, they
should not really break, should they ? The validity of the XML is not affected.

Besides the two possiilities already suggested, i.e.
(1) Use `WS_AFTER_CLOSE` in place of `WS_AFTER_OPEN` for an empty
`<node />`.

(2) Call the whitespace_cb three times in a row after an empty
node, with the values `WS_AFTER_OPEN, WS_BEFORE_CLOSE`,
`WS_AFTER_CLOSE` in that order (this may cause, in some existing apps,
whitespace_cb with wide catch clauses to insert too much WS).

there is a third option which may provide a better trade-off between
enhanced functionnality and change in existing apps:

(3) Add a fifth `where` value, say `MXML_WS_AFTER_EMPTY_NODE`, and
call the whitespace_cb a second time with that value, immediately
following the `MXML_WS_AFTER_OPEN`.

Whatever the future of this issue, thanks already for mini-xml
and its well written documentation!
