### ISSUE TITLE
Add capability to load/save with a generic callback

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/mxml#98]
Version: 3.x-feature
Original reporter: 

This enhancement would allow a generalized method to be used to load or save XML data with mini XML.

For example, a callback could be specified to new function entry points such as mxmlLoadStream, mxmlSAXLoadStream, mxmlSaveStream, etc.

The callback would consist of a function prototype defined like this:

```c
typedef int (*mxml_read_stream_cb_t)(void *,void *,unsigned int);
typedef int (*mxml_write_stream_cb_t)(void *,const void *,unsigned int);
```

For the read, the first argument would be the context passed through the entry point, the second argument would be the buffer used to store the data or the data to be written, and the third argument would be the number of bytes to read/write.

Thus, mxmlLoadStream would look like this:

```c
extern mxml_node_t *mxmlLoadStream
    (
    mxml_node_t *top, 
    mxml_read_stream_cb_t read_stream_cb,void *read_stream_context,
    mxml_type_t (*cb)(mxml_node_t *)
    );
```

Internally, in mxml-file.c new functions would be needed similar to the file descriptor entry points, where a generalized function is called rather than read/write.

In fact, this generalized method could potentially replace all of the separate getc and putc functions currently used (mxml_fd_getc, mxml_file_getc, etc.).

**Comment by michaelrsweet** [comment]
Deferring to a later release.

**Comment by woollybah** [comment]
I had to implement this because I needed the functionality for my language binding.

Thanks for the library :-)

**Comment by michaelrsweet** [comment]
[master 4e92848] Add mxmlLoadIO/mxmlSaveIO functions, merge everything under the new roof (Issue #98)
